from db.connection import get_db

def insert_message(user_query, answer):
    """
    Inserts a message (user query and answer) into the messages table.
    Args:
        user_query (str): The user's question.
        answer (str): The answer generated by the agent.
    Returns:
        None
    """
    conn = get_db()
    cur = conn.cursor()
    try:
        cur.execute(
            """
            INSERT INTO messages (content, username)
            VALUES (%s, %s)
            """,
            (answer, "Alice")
        )
        conn.commit()
    except Exception as e:
        print(f"Error inserting message: {e}")
    finally:
        cur.close()
        conn.close()
